name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          path: venv/
          key: pip-${{ hashFiles('requirements-dev.txt') }}-${{ hashFiles('requirements-dev.in') }}
      - name: Install dependencies
        run: ./scripts/setup.sh
      - name: Lint
        run: ./scripts/test.sh
